### ISSUE TITLE
Inquiry Regarding Generalization Testing Procedure

### ISSUE THREAD

**Issue by HJ-Xu** [dongliangcao/Unsupervised-Learning-of-Robust-Spectral-Shape-Matching#5]
Dear Author Cao,

I am writing to you regarding your research on Unsupervised Learning of Robust Spectral Shape Matching 2023 ToG. Firstly, I would like to express my appreciation for your contributions to the field.

I have been using the code provided on your GitHub for training on the faust_r dataset. I can replicate the results of FAUST TO FAUST mentioned in your paper. However, upon attempting to conduct generalization testing on the scape_r dataset using the pre-trained final.pth file obtained from the training on the faust_r dataset, I encountered unexpected results.

Specifically, when executing the command `python test.py --opt options/test/scape.yaml` with the `resume_state` parameter set to the final.pth file obtained from training on the faust_r dataset, I observed an average error of 0.062. This value significantly deviates from the 0.022 average error mentioned in your paper.
![image](https://github.com/dongliangcao/Unsupervised-Learning-of-Robust-Spectral-Shape-Matching/assets/44128932/7580576f-f322-4df8-9b99-645e9acb4820)

I kindly request guidance on the appropriate steps to take in order to achieve results consistent with those presented in your paper when conducting generalization testing on the scape_r dataset.

Thank you very much for your time and attention to this matter. I look forward to your prompt response.

Best regards,
HJ Xu

**Comment by dongliangcao** [comment]
Dear Xu,

Thanks a lot for your interest in our work. By default, we disable the test-time adaptation for FAUST TO FAUST and SCAPE TO SCAPE. In order to evaluate the generalisation performance of our method, such as FAUST TO SCAPE, you need to enable the test-time adaptation. To do it, you can check #3, which encountered the same issue as you described. One side note: As we described in our paper, we don't use Dirichlet loss for near-isometric datasets.

Best regards,
Dongliang
